### ISSUE TITLE
Sliders [Feature Request]

### ISSUE THREAD

**Issue by nomenon** [Idea-Software/SpotifyControls#4]
It would be cool if the sliders (volume and track timing) were working.
And for example, a click on the cover opened the main page

**Comment by Sergej-Popov** [comment]
Active sliders would be nice, but tricky to implement. So far could not find a way to simulate click at the specific area of the slider on the actual page.

**Comment by jeroenpeters1986** [comment]
The volume button has a 'mute' function now, am I correct?

**Comment by Sergej-Popov** [comment]
@jeroenpeters1986 yep mute button was easy to add.

**Comment by DRIVASS** [comment]
Supposedly this extension had working sliders. Can't confirm as the extension no longer works with Spotify, hasn't been updated since 2016. Perhaps some code in that extension could help you out.

https://chrome.google.com/webstore/detail/miniplay/dfddfiedihbijfeacjamchlliogmjjnd

https://github.com/jchen1/MiniPlay

**Comment by Sergej-Popov** [comment]
Nice find @SteveMalso . They are using `dispatchEvent(new MouseEvent('mousedown'` while I was trying `dispatchEvent(new MouseEvent('click'` experimented with it and mousedown actually works! Not sure when I will have time to implement this. Shouldn't be too much work though. Thanks!

**Comment by Sergej-Popov** [comment]
Fixed in version 2.0.2 bc540a2. Thanks, everyone!

**Comment by qirh** [comment]
Awesome work. Thank you Sergej!!
